version: "3.3"
services:
  mongo:
    restart: always
    image: mongo
    volumes:
      - glist-db-volume:/data/db
    ports:
      - "27017:27017"
  backend:
    build: ./backend/
    tty: true
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongo:27017
    volumes:
      - glist-log-volume:/var/glist/logs
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
  nginx:
    build: ./nginx
    tty: true
    links:
      - backend
    ports:
      - 80:80
volumes:
  glist-log-volume:
  glist-db-volume:
